### ISSUE TITLE
Morning Session PTP Code Review: To-do List

### ISSUE THREAD

**Issue by Hannziegel** [wayungi/ToDoListApp#3]
Hello @wayungi!
![](https://media.giphy.com/media/1jWaJ8RgySqOaPjl45/giphy-downsized.gif)

Your to-do list app is looking great! :sunglasses: Although we have found some room for improvement that could make your project look more professional.

### Suggestions for clean code improvement 

- [x] In line 30 of ui.js code, inside the trash.addEventListener you can see that you have 3 mentions for the same e.target.parentElement.parentElement.id, maybe would be a good change if you created a const to store that. That is going to make your code more clean. And you also can use a name for the const that mention what are you targeting, because if someone other than yourself read the code it will understand better what is the target.

**Comment by wayungi** [comment]
Recommended changes implemented
